import type { Professional } from '@/src/types/professional.types'

const avatar = (n: number) => `https://i.pravatar.cc/150?img=${n}`

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: '1',
    name: 'Carlos Eduardo Silva',
    profession: 'Mestre de Obras',
    rating: 4.9,
    reviewCount: 83,
    distanceKm: 1.2,
    available: true,
    phone: '(47) 99870-1234',
    bio: '22 anos de experiência em obras residenciais e comerciais. Especialista em estruturas de concreto e alvenaria.',
    location: { lat: -26.9194, lng: -49.0661, neighborhood: 'Centro', city: 'Blumenau' },
    completedJobs: 214,
    avatarInitials: 'CE',
    avatarUrl: avatar(11),
    tags: ['Concreto', 'Alvenaria', 'Estrutura'],
    hourlyRate: 95,
  },
  {
    id: '2',
    name: 'Roberto Mendes',
    profession: 'Eletricista',
    rating: 4.8,
    reviewCount: 61,
    distanceKm: 2.4,
    available: true,
    phone: '(47) 98765-5678',
    bio: 'Eletricista credenciado CREA. Instalações residenciais, comerciais e industriais. Laudos e projetos.',
    location: { lat: -26.9052, lng: -49.0748, neighborhood: 'Velha', city: 'Blumenau' },
    completedJobs: 178,
    avatarInitials: 'RM',
    avatarUrl: avatar(13),
    tags: ['CREA', 'Quadros', 'AR Condicionado'],
    hourlyRate: 85,
  },
  {
    id: '3',
    name: 'Josué Almeida',
    profession: 'Encanador',
    rating: 4.7,
    reviewCount: 44,
    distanceKm: 3.1,
    available: false,
    phone: '(47) 97654-9012',
    bio: 'Especializado em instalações hidráulicas, reparos emergenciais e sistemas de aquecimento solar.',
    location: { lat: -26.9226, lng: -49.0534, neighborhood: 'Victor Konder', city: 'Blumenau' },
    completedJobs: 132,
    avatarInitials: 'JA',
    avatarUrl: avatar(15),
    tags: ['Hidráulica', 'Solar', 'Emergência'],
  },
  {
    id: '4',
    name: 'Fernando Costa',
    profession: 'Pedreiro',
    rating: 4.6,
    reviewCount: 38,
    distanceKm: 1.8,
    available: true,
    phone: '(47) 96543-3456',
    bio: 'Especialista em revestimentos, argamassa e assentamento de tijolos. 15 anos de mercado.',
    location: { lat: -26.8838, lng: -49.0485, neighborhood: 'Itoupava Norte', city: 'Blumenau' },
    completedJobs: 97,
    avatarInitials: 'FC',
    avatarUrl: avatar(17),
    tags: ['Revestimento', 'Tijolo', 'Argamassa'],
    hourlyRate: 60,
  },
  {
    id: '5',
    name: 'Lucas Henrique Nunes',
    profession: 'Pintor',
    rating: 4.9,
    reviewCount: 72,
    distanceKm: 4.5,
    available: true,
    phone: '(47) 95432-7890',
    bio: 'Pintura interna, externa e texturas. Acabamento de alto padrão. Atendo condomínios e empresas.',
    location: { lat: -26.9348, lng: -49.0895, neighborhood: 'Garcia', city: 'Blumenau' },
    completedJobs: 203,
    avatarInitials: 'LH',
    avatarUrl: avatar(19),
    tags: ['Textura', 'Alto Padrão', 'Condomínios'],
    hourlyRate: 65,
  },
  {
    id: '6',
    name: 'Anderson Rocha',
    profession: 'Azulejista',
    rating: 4.5,
    reviewCount: 29,
    distanceKm: 2.9,
    available: true,
    phone: '(47) 94321-2345',
    bio: 'Assentamento de pisos, revestimentos cerâmicos e porcelanatos. Banheiros e cozinhas.',
    location: { lat: -26.9041, lng: -49.0842, neighborhood: 'Ponta Aguda', city: 'Blumenau' },
    completedJobs: 88,
    avatarInitials: 'AR',
    avatarUrl: avatar(21),
    tags: ['Porcelanato', 'Banheiro', 'Cozinha'],
  },
  {
    id: '7',
    name: 'Márcio Pereira',
    profession: 'Gesseiro',
    rating: 4.7,
    reviewCount: 51,
    distanceKm: 5.2,
    available: false,
    phone: '(47) 93210-6789',
    bio: 'Forros de gesso, sancas, molduras e drywall. Projetos residenciais e comerciais.',
    location: { lat: -26.9399, lng: -49.0398, neighborhood: 'Escola Agrícola', city: 'Blumenau' },
    completedJobs: 147,
    avatarInitials: 'MP',
    avatarUrl: avatar(23),
    tags: ['Drywall', 'Sancas', 'Molduras'],
  },
  {
    id: '8',
    name: 'Paulo Henrique Dias',
    profession: 'Marceneiro',
    rating: 4.8,
    reviewCount: 66,
    distanceKm: 3.7,
    available: true,
    phone: '(47) 92109-0123',
    bio: 'Móveis planejados, portas, janelas e deck. Madeira maciça e MDF de qualidade.',
    location: { lat: -26.9498, lng: -49.0647, neighborhood: 'Bom Retiro', city: 'Blumenau' },
    completedJobs: 189,
    avatarInitials: 'PH',
    avatarUrl: avatar(25),
    tags: ['Planejados', 'Deck', 'MDF'],
    hourlyRate: 100,
  },
  {
    id: '9',
    name: 'Thiago Ferreira',
    profession: 'Pedreiro',
    rating: 4.4,
    reviewCount: 22,
    distanceKm: 6.1,
    available: true,
    phone: '(47) 91098-4567',
    bio: 'Construção e reformas em geral. Fundações, contrapisos e alvenaria estrutural.',
    location: { lat: -26.8752, lng: -49.0599, neighborhood: 'Fortaleza', city: 'Blumenau' },
    completedJobs: 54,
    avatarInitials: 'TF',
    avatarUrl: avatar(27),
    tags: ['Fundação', 'Contrapiso', 'Reforma'],
  },
  {
    id: '10',
    name: 'Diego Santana',
    profession: 'Eletricista',
    rating: 4.6,
    reviewCount: 35,
    distanceKm: 7.4,
    available: false,
    phone: '(47) 90987-8901',
    bio: 'Instalações de câmeras, alarmes, automação residencial e redes de dados.',
    location: { lat: -26.9275, lng: -49.0734, neighborhood: 'Vila Nova', city: 'Blumenau' },
    completedJobs: 112,
    avatarInitials: 'DS',
    avatarUrl: avatar(29),
    tags: ['CFTV', 'Alarme', 'Automação'],
  },
  {
    id: '11',
    name: 'Bruno Oliveira',
    profession: 'Mestre de Obras',
    rating: 4.8,
    reviewCount: 57,
    distanceKm: 4.8,
    available: true,
    phone: '(47) 99876-1111',
    bio: 'Gerenciamento completo de obras. Contratação de equipes, cronograma e controle de qualidade.',
    location: { lat: -26.918, lng: -49.082, neighborhood: 'Glória', city: 'Blumenau' },
    completedJobs: 167,
    avatarInitials: 'BO',
    avatarUrl: avatar(31),
    tags: ['Gerência', 'Cronograma', 'Equipes'],
    hourlyRate: 90,
  },
  {
    id: '12',
    name: 'Rafael Gomes',
    profession: 'Pintor',
    rating: 4.5,
    reviewCount: 41,
    distanceKm: 2.2,
    available: true,
    phone: '(47) 98765-2222',
    bio: 'Pintura de fachadas, impermeabilização e recuperação de estruturas. Trabalho em altura.',
    location: { lat: -26.935, lng: -49.055, neighborhood: 'Progresso', city: 'Blumenau' },
    completedJobs: 123,
    avatarInitials: 'RG',
    avatarUrl: avatar(33),
    tags: ['Fachada', 'Impermeabilização', 'Altura'],
  },
  {
    id: '13',
    name: 'Vinicius Cardoso',
    profession: 'Encanador',
    rating: 4.9,
    reviewCount: 78,
    distanceKm: 3.3,
    available: true,
    phone: '(47) 97654-3333',
    bio: 'Encanador certificado. Tubulações de gás, água quente e fria. Piscinas e spas.',
    location: { lat: -26.915, lng: -49.035, neighborhood: 'Itoupavazinha', city: 'Blumenau' },
    completedJobs: 231,
    avatarInitials: 'VC',
    avatarUrl: avatar(35),
    tags: ['Gás', 'Piscina', 'Certificado'],
    hourlyRate: 75,
  },
  {
    id: '14',
    name: 'Alex Teixeira',
    profession: 'Azulejista',
    rating: 4.7,
    reviewCount: 48,
    distanceKm: 5.6,
    available: false,
    phone: '(47) 96543-4444',
    bio: 'Especialista em materiais de alto padrão. Mármore, granito e pedra natural.',
    location: { lat: -26.945, lng: -49.08, neighborhood: 'Água Verde', city: 'Blumenau' },
    completedJobs: 156,
    avatarInitials: 'AT',
    avatarUrl: avatar(37),
    tags: ['Mármore', 'Granito', 'Pedra Natural'],
  },
  {
    id: '15',
    name: 'Gabriel Nascimento',
    profession: 'Gesseiro',
    rating: 4.6,
    reviewCount: 33,
    distanceKm: 8.1,
    available: true,
    phone: '(47) 95432-5555',
    bio: 'Gesso projetado, reboco e acabamentos finos. Rápido e com garantia no serviço.',
    location: { lat: -26.865, lng: -49.09, neighborhood: 'Badenfurt', city: 'Blumenau' },
    completedJobs: 94,
    avatarInitials: 'GN',
    avatarUrl: avatar(39),
    tags: ['Projetado', 'Reboco', 'Garantia'],
  },
  {
    id: '16',
    name: 'Felipe Araújo',
    profession: 'Marceneiro',
    rating: 4.9,
    reviewCount: 89,
    distanceKm: 6.3,
    available: true,
    phone: '(47) 94321-6666',
    bio: 'Móveis sob medida para cozinhas, quartos e escritórios. Design moderno e acabamento premium.',
    location: { lat: -26.91, lng: -49.1, neighborhood: 'Jardim Blumenau', city: 'Blumenau' },
    completedJobs: 278,
    avatarInitials: 'FA',
    avatarUrl: avatar(41),
    tags: ['Sob Medida', 'Design', 'Premium'],
    hourlyRate: 120,
  },
]
